version: "3.2"

services:
  serviio:
    build: .
    ports:
      - "23423:23423/tcp"
      - "23424:23424/tcp"
      - "8895:8895/tcp"
      - "1900:1900/udp"
    volumes:
      - /var/log/serviio:/opt/serviio/log
      - /var/serviio/library:/opt/serviio/library
      - /media:/medialib
