version: "3.2"

services:
  serviio:
    build: .
    network_mode: host  
    volumes:
      - /var/log/serviio:/opt/serviio/log
      - /var/serviio/library:/opt/serviio/library
      - /media:/medialib
    container_name: docker-serviio
